"""Runtime settings for the K230 photo capture app."""

SAVE_DIR_CANDIDATES = ("photos", "/photos")

AUTO_CAPTURE_INTERVAL_MS = 10_000

PREVIEW_FRAMESIZE = "VGA"
CAPTURE_FRAMESIZE = "VGA"
PIXFORMAT = "RGB565"
JPEG_QUALITY = 90

ENABLE_PREVIEW = True
ENABLE_AUTO_CAPTURE = True
ENABLE_KEY_CAPTURE = True

KEY0_PIN = "KEY0"
KEY1_PIN = "KEY1"

AUTO_PREFIX = "auto"
KEY0_PREFIX = "key0"
KEY1_PREFIX = "key1"
